### ISSUE TITLE
The script doesn't work

### ISSUE THREAD

**Issue by EhuddR** [ronjouch/whoarder#1]
Hi! I would like to use your script for my Kindle annotations but it does not seems to do anything at all. Maybe I just loose some step in the process or something.
Can you please help me?

Best regards.

**Comment by ronjouch** [comment]
Hi @EhuddR! I haven't touched whoarder in a looooooooong time, and am not surprised it's no longer working.

I suggest you take a look at the project's list of forks at https://github.com/ronjouch/whoarder/network/members . Maybe one of them did the maintenance job I'm not doing, and will work as of today.

Then, if you have the time to do so, I have one favor to ask you: if you find a fork that works and stands out as well-maintained, can you please get in touch with the fork's author, asking them to file a PR here for me to integrate their maintenance changes? I'll then publish a new pip release.

Thanks.

**Comment by EhuddR** [comment]
It's a pity, the script looked great. I did check the other forks but they don't seem to work. Thank you anyway.
